GET http://localhost:3000/games

###

GET http://localhost:3000/games/ids
Content-Type: application/json

{
  "ids": ["668abbe257dfd972da8bfee5"]
}

###

GET http://localhost:3000/games/developer/668aba7857dfd972da8bfeda

###

GET http://localhost:3000/games/categories
Content-Type: application/json

{
  "categories": ["Adventure"]
}

###

POST http://localhost:3000/games
Content-Type: application/json

{
  "name": "Example Game",
  "price": 59.99,
  "image": "http://example.com/image.jpg",
  "description": "An example game description",
  "developerId": "60d0fe4f5311236168a109cc",
  "platformLinks": [
    {
      "platform": "Steam",
      "url": "http://store.steampowered.com/app/example"
    }
  ],
  "releaseDate": "2023-07-01T00:00:00.000Z"
}

###

PUT http://localhost:3000/games/668adb87ab102ac7568efdc9
Content-Type: application/json

{
  "price": 49.99,
  "description": "An updated game description"
}

###

DELETE http://localhost:3000/games/668adb87ab102ac7568efdc9
