POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Lior"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGlvciIsImlhdCI6MTcyMDExODgxOH0.jDZLLJ-s9WTlrbCH83bqGYDtKbv_S3xMGtDE5IoPUUA"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGlvciIsImlhdCI6MTcyMDExNTY0NH0.1oj6I7l8g1PtG1Wo0G8Rlm3uSBYYPtzbuvK4mUiZZ-Q