GET http://localhost:3000/users

###

GET http://localhost:3000/users/668acf7fa5c756ee8df9df04

###

POST http://localhost:3000/users/email
Content-Type: application/json

{
    "email": "liorhassin3@gmail.com"
}

###

POST http://localhost:3000/users/user-details
Content-Type: application/json

{
    "token": ""

}

###

POST http://localhost:3000/auth/register/
Content-Type: application/json

{
    "name": "Lior Hassin",
    "email": "liorhassin1@gmail.com",
    "password": "Lior123456!",
    "birthDate": "06-22-1997",
    "profileImage": "nothing.png"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "liorhassin1@gmail.com",
    "password": "Lior123456!"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OGFkOTRkMDg1YTNiYzMzNWJmY2M0MiIsImlhdCI6MTcyMDM3NTYzOCwiZXhwIjoxNzIwNzM1NjM4fQ.S0hoisye-BR-oXZAF90V_8JnUQW0_qB9OOCclMk2-8w"
}
